server:
  port: 7001
  servlet:
    context-path: /devspringprj

spring:
  mvc:
    view:
      prefix: /WEB-INF/template/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: donbq
  output:
    ansi:
      enabled: always

mybatis:
  type-aliases-package: dev.study.devspringprj
  mapper-locations: classpath:*.xml
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500

logging:
  config: classpath:log4j2.yml