server:
  port: 7001
  servlet:
    context-path: /devspringprj

spring:
  mvc:
    view:
      prefix: /WEB-INF/template/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: donbq

mybatis:
  type-aliases-package: dev.study.devspringprj
  mapper-locations: classpath:*.xml

logging:
  config: classpath:log4j2.yml

mybatis:
  configuration:
    map-underscore-to-camel-case: true  